{% if salt['elife.cfg']('cfn.outputs.RDSHost') %}
rds-snapshot:
    - {{ salt['elife.cfg']('project.rds_instance_id') }}
{% else %}
postgresql-database:
    - {{ salt['elife.cfg']('project.rds_dbname') or pillar.elife.db.app.name }}
{% endif %}
